/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const BoqItem = IDL.Record({
  'id' : IDL.Nat,
  'plannedQuantity' : IDL.Float64,
  'unit' : IDL.Text,
  'description' : IDL.Text,
  'projectId' : IDL.Nat,
  'itemName' : IDL.Text,
  'usedQuantity' : IDL.Float64,
  'unitRate' : IDL.Float64,
});
export const Time = IDL.Int;
export const CostEntry = IDL.Record({
  'id' : IDL.Nat,
  'date' : Time,
  'description' : IDL.Text,
  'projectId' : IDL.Nat,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});
export const Labour = IDL.Record({
  'id' : IDL.Nat,
  'dailyWage' : IDL.Float64,
  'role' : IDL.Text,
  'projectId' : IDL.Nat,
  'daysWorked' : IDL.Float64,
  'workerName' : IDL.Text,
});
export const Material = IDL.Record({
  'id' : IDL.Nat,
  'supplier' : IDL.Text,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'projectId' : IDL.Nat,
  'quantity' : IDL.Float64,
  'unitCost' : IDL.Float64,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ProjectPhoto = IDL.Record({
  'id' : IDL.Nat,
  'description' : IDL.Text,
  'dateUploaded' : Time,
  'imageUrl' : ExternalBlob,
  'projectId' : IDL.Nat,
  'reportId' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProjectStatus = IDL.Variant({
  'active' : IDL.Null,
  'completed' : IDL.Null,
  'onHold' : IDL.Null,
  'planning' : IDL.Null,
});
export const ProjectStage = IDL.Variant({
  'foundation' : IDL.Null,
  'structure' : IDL.Null,
  'completed' : IDL.Null,
  'finishing' : IDL.Null,
  'planning' : IDL.Null,
});
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'estimatedDurationDays' : IDL.Float64,
  'status' : ProjectStatus,
  'endDate' : Time,
  'clientName' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'currentProgressPercentage' : IDL.Float64,
  'stage' : ProjectStage,
  'budget' : IDL.Float64,
  'location' : IDL.Text,
  'startDate' : Time,
});
export const DailySiteReport = IDL.Record({
  'id' : IDL.Nat,
  'workersOnSite' : IDL.Nat,
  'date' : Time,
  'hoursWorked' : IDL.Float64,
  'activities' : IDL.Text,
  'projectId' : IDL.Nat,
  'notes' : IDL.Text,
  'weather' : IDL.Text,
});
export const ProjectCostSummary = IDL.Record({
  'status' : ProjectStatus,
  'remainingBudget' : IDL.Float64,
  'projectName' : IDL.Text,
  'totalSpent' : IDL.Float64,
  'labourCost' : IDL.Float64,
  'projectId' : IDL.Nat,
  'materialsCost' : IDL.Float64,
  'budgetPct' : IDL.Float64,
  'budget' : IDL.Float64,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBOQItem' : IDL.Func([BoqItem], [IDL.Nat], []),
  'addCostEntry' : IDL.Func([CostEntry], [IDL.Nat], []),
  'addLabour' : IDL.Func([Labour], [IDL.Nat], []),
  'addMaterial' : IDL.Func([Material], [IDL.Nat], []),
  'addProjectPhoto' : IDL.Func([ProjectPhoto], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProject' : IDL.Func([Project], [IDL.Nat], []),
  'createReport' : IDL.Func([DailySiteReport], [IDL.Nat], []),
  'deleteBOQItem' : IDL.Func([IDL.Nat], [], []),
  'deleteCostEntry' : IDL.Func([IDL.Nat], [], []),
  'deleteLabour' : IDL.Func([IDL.Nat], [], []),
  'deleteMaterial' : IDL.Func([IDL.Nat], [], []),
  'deleteProject' : IDL.Func([IDL.Nat], [], []),
  'deleteProjectPhoto' : IDL.Func([IDL.Nat], [], []),
  'deleteReport' : IDL.Func([IDL.Nat], [], []),
  'getAllProjectCostSummaries' : IDL.Func(
      [],
      [IDL.Vec(ProjectCostSummary)],
      ['query'],
    ),
  'getBoqItemsByProject' : IDL.Func([IDL.Nat], [IDL.Vec(BoqItem)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCostEntriesByProject' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(CostEntry)],
      ['query'],
    ),
  'getDashboardStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'foundationCount' : IDL.Nat,
          'onHoldCount' : IDL.Nat,
          'structureCount' : IDL.Nat,
          'completedCount' : IDL.Nat,
          'totalSpent' : IDL.Float64,
          'totalBudget' : IDL.Float64,
          'activeCount' : IDL.Nat,
          'planningCount' : IDL.Nat,
          'finishingCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getLabourByProject' : IDL.Func([IDL.Nat], [IDL.Vec(Labour)], ['query']),
  'getMaterialsByProject' : IDL.Func([IDL.Nat], [IDL.Vec(Material)], ['query']),
  'getProjectById' : IDL.Func([IDL.Nat], [IDL.Opt(Project)], ['query']),
  'getProjectCostSummary' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(ProjectCostSummary)],
      ['query'],
    ),
  'getProjectPhotosByProject' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ProjectPhoto)],
      ['query'],
    ),
  'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getReportsByProject' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(DailySiteReport)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBOQItem' : IDL.Func([BoqItem], [], []),
  'updateCostEntry' : IDL.Func([CostEntry], [], []),
  'updateLabour' : IDL.Func([Labour], [], []),
  'updateMaterial' : IDL.Func([Material], [], []),
  'updateProject' : IDL.Func([IDL.Nat, Project], [], []),
  'updateReport' : IDL.Func([DailySiteReport], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const BoqItem = IDL.Record({
    'id' : IDL.Nat,
    'plannedQuantity' : IDL.Float64,
    'unit' : IDL.Text,
    'description' : IDL.Text,
    'projectId' : IDL.Nat,
    'itemName' : IDL.Text,
    'usedQuantity' : IDL.Float64,
    'unitRate' : IDL.Float64,
  });
  const Time = IDL.Int;
  const CostEntry = IDL.Record({
    'id' : IDL.Nat,
    'date' : Time,
    'description' : IDL.Text,
    'projectId' : IDL.Nat,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const Labour = IDL.Record({
    'id' : IDL.Nat,
    'dailyWage' : IDL.Float64,
    'role' : IDL.Text,
    'projectId' : IDL.Nat,
    'daysWorked' : IDL.Float64,
    'workerName' : IDL.Text,
  });
  const Material = IDL.Record({
    'id' : IDL.Nat,
    'supplier' : IDL.Text,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'projectId' : IDL.Nat,
    'quantity' : IDL.Float64,
    'unitCost' : IDL.Float64,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ProjectPhoto = IDL.Record({
    'id' : IDL.Nat,
    'description' : IDL.Text,
    'dateUploaded' : Time,
    'imageUrl' : ExternalBlob,
    'projectId' : IDL.Nat,
    'reportId' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProjectStatus = IDL.Variant({
    'active' : IDL.Null,
    'completed' : IDL.Null,
    'onHold' : IDL.Null,
    'planning' : IDL.Null,
  });
  const ProjectStage = IDL.Variant({
    'foundation' : IDL.Null,
    'structure' : IDL.Null,
    'completed' : IDL.Null,
    'finishing' : IDL.Null,
    'planning' : IDL.Null,
  });
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'estimatedDurationDays' : IDL.Float64,
    'status' : ProjectStatus,
    'endDate' : Time,
    'clientName' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'currentProgressPercentage' : IDL.Float64,
    'stage' : ProjectStage,
    'budget' : IDL.Float64,
    'location' : IDL.Text,
    'startDate' : Time,
  });
  const DailySiteReport = IDL.Record({
    'id' : IDL.Nat,
    'workersOnSite' : IDL.Nat,
    'date' : Time,
    'hoursWorked' : IDL.Float64,
    'activities' : IDL.Text,
    'projectId' : IDL.Nat,
    'notes' : IDL.Text,
    'weather' : IDL.Text,
  });
  const ProjectCostSummary = IDL.Record({
    'status' : ProjectStatus,
    'remainingBudget' : IDL.Float64,
    'projectName' : IDL.Text,
    'totalSpent' : IDL.Float64,
    'labourCost' : IDL.Float64,
    'projectId' : IDL.Nat,
    'materialsCost' : IDL.Float64,
    'budgetPct' : IDL.Float64,
    'budget' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBOQItem' : IDL.Func([BoqItem], [IDL.Nat], []),
    'addCostEntry' : IDL.Func([CostEntry], [IDL.Nat], []),
    'addLabour' : IDL.Func([Labour], [IDL.Nat], []),
    'addMaterial' : IDL.Func([Material], [IDL.Nat], []),
    'addProjectPhoto' : IDL.Func([ProjectPhoto], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProject' : IDL.Func([Project], [IDL.Nat], []),
    'createReport' : IDL.Func([DailySiteReport], [IDL.Nat], []),
    'deleteBOQItem' : IDL.Func([IDL.Nat], [], []),
    'deleteCostEntry' : IDL.Func([IDL.Nat], [], []),
    'deleteLabour' : IDL.Func([IDL.Nat], [], []),
    'deleteMaterial' : IDL.Func([IDL.Nat], [], []),
    'deleteProject' : IDL.Func([IDL.Nat], [], []),
    'deleteProjectPhoto' : IDL.Func([IDL.Nat], [], []),
    'deleteReport' : IDL.Func([IDL.Nat], [], []),
    'getAllProjectCostSummaries' : IDL.Func(
        [],
        [IDL.Vec(ProjectCostSummary)],
        ['query'],
      ),
    'getBoqItemsByProject' : IDL.Func([IDL.Nat], [IDL.Vec(BoqItem)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCostEntriesByProject' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(CostEntry)],
        ['query'],
      ),
    'getDashboardStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'foundationCount' : IDL.Nat,
            'onHoldCount' : IDL.Nat,
            'structureCount' : IDL.Nat,
            'completedCount' : IDL.Nat,
            'totalSpent' : IDL.Float64,
            'totalBudget' : IDL.Float64,
            'activeCount' : IDL.Nat,
            'planningCount' : IDL.Nat,
            'finishingCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getLabourByProject' : IDL.Func([IDL.Nat], [IDL.Vec(Labour)], ['query']),
    'getMaterialsByProject' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Material)],
        ['query'],
      ),
    'getProjectById' : IDL.Func([IDL.Nat], [IDL.Opt(Project)], ['query']),
    'getProjectCostSummary' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ProjectCostSummary)],
        ['query'],
      ),
    'getProjectPhotosByProject' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ProjectPhoto)],
        ['query'],
      ),
    'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getReportsByProject' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(DailySiteReport)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBOQItem' : IDL.Func([BoqItem], [], []),
    'updateCostEntry' : IDL.Func([CostEntry], [], []),
    'updateLabour' : IDL.Func([Labour], [], []),
    'updateMaterial' : IDL.Func([Material], [], []),
    'updateProject' : IDL.Func([IDL.Nat, Project], [], []),
    'updateReport' : IDL.Func([DailySiteReport], [], []),
  });
};

export const init = ({ IDL }) => { return []; };