/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CostEntry {
  'id' : bigint,
  'date' : Time,
  'description' : string,
  'projectId' : bigint,
  'category' : string,
  'amount' : number,
}
export interface DailySiteReport {
  'id' : bigint,
  'workersOnSite' : bigint,
  'date' : Time,
  'hoursWorked' : number,
  'activities' : string,
  'projectId' : bigint,
  'notes' : string,
  'weather' : string,
}
export interface Material {
  'id' : bigint,
  'supplier' : string,
  'name' : string,
  'unit' : string,
  'projectId' : bigint,
  'quantity' : number,
  'unitCost' : number,
}
export interface Project {
  'id' : bigint,
  'status' : ProjectStatus,
  'endDate' : Time,
  'name' : string,
  'description' : string,
  'budget' : number,
  'location' : string,
  'startDate' : Time,
}
export type ProjectStatus = { 'active' : null } |
  { 'completed' : null } |
  { 'onHold' : null } |
  { 'planning' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCostEntry' : ActorMethod<[CostEntry], bigint>,
  'createMaterial' : ActorMethod<[Material], bigint>,
  'createProject' : ActorMethod<[Project], bigint>,
  'createReport' : ActorMethod<[DailySiteReport], bigint>,
  'deleteCostEntry' : ActorMethod<[bigint], undefined>,
  'deleteMaterial' : ActorMethod<[bigint], undefined>,
  'deleteProject' : ActorMethod<[bigint], undefined>,
  'deleteReport' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCostEntry' : ActorMethod<[bigint], [] | [CostEntry]>,
  'getCostsByProject' : ActorMethod<[bigint], Array<CostEntry>>,
  'getDashboardStats' : ActorMethod<
    [],
    {
      'onHoldCount' : bigint,
      'completedCount' : bigint,
      'totalSpent' : number,
      'totalBudget' : number,
      'activeCount' : bigint,
      'planningCount' : bigint,
    }
  >,
  'getMaterial' : ActorMethod<[bigint], [] | [Material]>,
  'getMaterialsByProject' : ActorMethod<[bigint], Array<Material>>,
  'getProject' : ActorMethod<[bigint], [] | [Project]>,
  'getProjectSummary' : ActorMethod<
    [bigint],
    {
      'totalMaterialCost' : number,
      'totalCostEntries' : number,
      'variance' : number,
      'totalSpent' : number,
      'budget' : number,
    }
  >,
  'getProjectsByStatus' : ActorMethod<[ProjectStatus], Array<Project>>,
  'getReport' : ActorMethod<[bigint], [] | [DailySiteReport]>,
  'getReportsByProject' : ActorMethod<[bigint], Array<DailySiteReport>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCostEntry' : ActorMethod<[CostEntry], undefined>,
  'updateMaterial' : ActorMethod<[Material], undefined>,
  'updateProject' : ActorMethod<[Project], undefined>,
  'updateReport' : ActorMethod<[DailySiteReport], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];