/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BoqItem {
  'id' : bigint,
  'plannedQuantity' : number,
  'unit' : string,
  'description' : string,
  'projectId' : bigint,
  'itemName' : string,
  'usedQuantity' : number,
  'unitRate' : number,
}
export interface CostEntry {
  'id' : bigint,
  'date' : Time,
  'description' : string,
  'projectId' : bigint,
  'category' : string,
  'amount' : number,
}
export interface DailySiteReport {
  'id' : bigint,
  'workersOnSite' : bigint,
  'date' : Time,
  'hoursWorked' : number,
  'activities' : string,
  'projectId' : bigint,
  'notes' : string,
  'weather' : string,
}
export type ExternalBlob = Uint8Array;
export interface Labour {
  'id' : bigint,
  'dailyWage' : number,
  'role' : string,
  'projectId' : bigint,
  'daysWorked' : number,
  'workerName' : string,
}
export interface Material {
  'id' : bigint,
  'supplier' : string,
  'name' : string,
  'unit' : string,
  'projectId' : bigint,
  'quantity' : number,
  'unitCost' : number,
}
export interface Project {
  'id' : bigint,
  'estimatedDurationDays' : number,
  'status' : ProjectStatus,
  'endDate' : Time,
  'clientName' : string,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'currentProgressPercentage' : number,
  'stage' : ProjectStage,
  'budget' : number,
  'location' : string,
  'startDate' : Time,
}
export interface ProjectCostSummary {
  'status' : ProjectStatus,
  'remainingBudget' : number,
  'projectName' : string,
  'totalSpent' : number,
  'labourCost' : number,
  'projectId' : bigint,
  'materialsCost' : number,
  'budgetPct' : number,
  'budget' : number,
}
export interface ProjectPhoto {
  'id' : bigint,
  'description' : string,
  'dateUploaded' : Time,
  'imageUrl' : ExternalBlob,
  'projectId' : bigint,
  'reportId' : bigint,
}
export type ProjectStage = { 'foundation' : null } |
  { 'structure' : null } |
  { 'completed' : null } |
  { 'finishing' : null } |
  { 'planning' : null };
export type ProjectStatus = { 'active' : null } |
  { 'completed' : null } |
  { 'onHold' : null } |
  { 'planning' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBOQItem' : ActorMethod<[BoqItem], bigint>,
  'addCostEntry' : ActorMethod<[CostEntry], bigint>,
  'addLabour' : ActorMethod<[Labour], bigint>,
  'addMaterial' : ActorMethod<[Material], bigint>,
  'addProjectPhoto' : ActorMethod<[ProjectPhoto], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProject' : ActorMethod<[Project], bigint>,
  'createReport' : ActorMethod<[DailySiteReport], bigint>,
  'deleteBOQItem' : ActorMethod<[bigint], undefined>,
  'deleteCostEntry' : ActorMethod<[bigint], undefined>,
  'deleteLabour' : ActorMethod<[bigint], undefined>,
  'deleteMaterial' : ActorMethod<[bigint], undefined>,
  'deleteProject' : ActorMethod<[bigint], undefined>,
  /**
   * / Deletes a project photo by id
   * / #user permission required (any authenticated user)
   */
  'deleteProjectPhoto' : ActorMethod<[bigint], undefined>,
  'deleteReport' : ActorMethod<[bigint], undefined>,
  'getAllProjectCostSummaries' : ActorMethod<[], Array<ProjectCostSummary>>,
  'getBoqItemsByProject' : ActorMethod<[bigint], Array<BoqItem>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCostEntriesByProject' : ActorMethod<[bigint], Array<CostEntry>>,
  'getDashboardStats' : ActorMethod<
    [],
    {
      'foundationCount' : bigint,
      'onHoldCount' : bigint,
      'structureCount' : bigint,
      'completedCount' : bigint,
      'totalSpent' : number,
      'totalBudget' : number,
      'activeCount' : bigint,
      'planningCount' : bigint,
      'finishingCount' : bigint,
    }
  >,
  'getLabourByProject' : ActorMethod<[bigint], Array<Labour>>,
  'getMaterialsByProject' : ActorMethod<[bigint], Array<Material>>,
  'getProjectById' : ActorMethod<[bigint], [] | [Project]>,
  'getProjectCostSummary' : ActorMethod<[bigint], [] | [ProjectCostSummary]>,
  'getProjectPhotosByProject' : ActorMethod<[bigint], Array<ProjectPhoto>>,
  'getProjects' : ActorMethod<[], Array<Project>>,
  'getReportsByProject' : ActorMethod<[bigint], Array<DailySiteReport>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBOQItem' : ActorMethod<[BoqItem], undefined>,
  'updateCostEntry' : ActorMethod<[CostEntry], undefined>,
  'updateLabour' : ActorMethod<[Labour], undefined>,
  'updateMaterial' : ActorMethod<[Material], undefined>,
  'updateProject' : ActorMethod<[bigint, Project], undefined>,
  'updateReport' : ActorMethod<[DailySiteReport], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];