/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const CostEntry = IDL.Record({
  'id' : IDL.Nat,
  'date' : Time,
  'description' : IDL.Text,
  'projectId' : IDL.Nat,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});
export const Material = IDL.Record({
  'id' : IDL.Nat,
  'supplier' : IDL.Text,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'projectId' : IDL.Nat,
  'quantity' : IDL.Float64,
  'unitCost' : IDL.Float64,
});
export const ProjectStatus = IDL.Variant({
  'active' : IDL.Null,
  'completed' : IDL.Null,
  'onHold' : IDL.Null,
  'planning' : IDL.Null,
});
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'status' : ProjectStatus,
  'endDate' : Time,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'budget' : IDL.Float64,
  'location' : IDL.Text,
  'startDate' : Time,
});
export const DailySiteReport = IDL.Record({
  'id' : IDL.Nat,
  'workersOnSite' : IDL.Nat,
  'date' : Time,
  'hoursWorked' : IDL.Float64,
  'activities' : IDL.Text,
  'projectId' : IDL.Nat,
  'notes' : IDL.Text,
  'weather' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCostEntry' : IDL.Func([CostEntry], [IDL.Nat], []),
  'createMaterial' : IDL.Func([Material], [IDL.Nat], []),
  'createProject' : IDL.Func([Project], [IDL.Nat], []),
  'createReport' : IDL.Func([DailySiteReport], [IDL.Nat], []),
  'deleteCostEntry' : IDL.Func([IDL.Nat], [], []),
  'deleteMaterial' : IDL.Func([IDL.Nat], [], []),
  'deleteProject' : IDL.Func([IDL.Nat], [], []),
  'deleteReport' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCostEntry' : IDL.Func([IDL.Nat], [IDL.Opt(CostEntry)], ['query']),
  'getCostsByProject' : IDL.Func([IDL.Nat], [IDL.Vec(CostEntry)], ['query']),
  'getDashboardStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'onHoldCount' : IDL.Nat,
          'completedCount' : IDL.Nat,
          'totalSpent' : IDL.Float64,
          'totalBudget' : IDL.Float64,
          'activeCount' : IDL.Nat,
          'planningCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getMaterial' : IDL.Func([IDL.Nat], [IDL.Opt(Material)], ['query']),
  'getMaterialsByProject' : IDL.Func([IDL.Nat], [IDL.Vec(Material)], ['query']),
  'getProject' : IDL.Func([IDL.Nat], [IDL.Opt(Project)], ['query']),
  'getProjectSummary' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Record({
          'totalMaterialCost' : IDL.Float64,
          'totalCostEntries' : IDL.Float64,
          'variance' : IDL.Float64,
          'totalSpent' : IDL.Float64,
          'budget' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getProjectsByStatus' : IDL.Func(
      [ProjectStatus],
      [IDL.Vec(Project)],
      ['query'],
    ),
  'getReport' : IDL.Func([IDL.Nat], [IDL.Opt(DailySiteReport)], ['query']),
  'getReportsByProject' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(DailySiteReport)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCostEntry' : IDL.Func([CostEntry], [], []),
  'updateMaterial' : IDL.Func([Material], [], []),
  'updateProject' : IDL.Func([Project], [], []),
  'updateReport' : IDL.Func([DailySiteReport], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const CostEntry = IDL.Record({
    'id' : IDL.Nat,
    'date' : Time,
    'description' : IDL.Text,
    'projectId' : IDL.Nat,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const Material = IDL.Record({
    'id' : IDL.Nat,
    'supplier' : IDL.Text,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'projectId' : IDL.Nat,
    'quantity' : IDL.Float64,
    'unitCost' : IDL.Float64,
  });
  const ProjectStatus = IDL.Variant({
    'active' : IDL.Null,
    'completed' : IDL.Null,
    'onHold' : IDL.Null,
    'planning' : IDL.Null,
  });
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'status' : ProjectStatus,
    'endDate' : Time,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'budget' : IDL.Float64,
    'location' : IDL.Text,
    'startDate' : Time,
  });
  const DailySiteReport = IDL.Record({
    'id' : IDL.Nat,
    'workersOnSite' : IDL.Nat,
    'date' : Time,
    'hoursWorked' : IDL.Float64,
    'activities' : IDL.Text,
    'projectId' : IDL.Nat,
    'notes' : IDL.Text,
    'weather' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCostEntry' : IDL.Func([CostEntry], [IDL.Nat], []),
    'createMaterial' : IDL.Func([Material], [IDL.Nat], []),
    'createProject' : IDL.Func([Project], [IDL.Nat], []),
    'createReport' : IDL.Func([DailySiteReport], [IDL.Nat], []),
    'deleteCostEntry' : IDL.Func([IDL.Nat], [], []),
    'deleteMaterial' : IDL.Func([IDL.Nat], [], []),
    'deleteProject' : IDL.Func([IDL.Nat], [], []),
    'deleteReport' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCostEntry' : IDL.Func([IDL.Nat], [IDL.Opt(CostEntry)], ['query']),
    'getCostsByProject' : IDL.Func([IDL.Nat], [IDL.Vec(CostEntry)], ['query']),
    'getDashboardStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'onHoldCount' : IDL.Nat,
            'completedCount' : IDL.Nat,
            'totalSpent' : IDL.Float64,
            'totalBudget' : IDL.Float64,
            'activeCount' : IDL.Nat,
            'planningCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getMaterial' : IDL.Func([IDL.Nat], [IDL.Opt(Material)], ['query']),
    'getMaterialsByProject' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Material)],
        ['query'],
      ),
    'getProject' : IDL.Func([IDL.Nat], [IDL.Opt(Project)], ['query']),
    'getProjectSummary' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Record({
            'totalMaterialCost' : IDL.Float64,
            'totalCostEntries' : IDL.Float64,
            'variance' : IDL.Float64,
            'totalSpent' : IDL.Float64,
            'budget' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getProjectsByStatus' : IDL.Func(
        [ProjectStatus],
        [IDL.Vec(Project)],
        ['query'],
      ),
    'getReport' : IDL.Func([IDL.Nat], [IDL.Opt(DailySiteReport)], ['query']),
    'getReportsByProject' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(DailySiteReport)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCostEntry' : IDL.Func([CostEntry], [], []),
    'updateMaterial' : IDL.Func([Material], [], []),
    'updateProject' : IDL.Func([Project], [], []),
    'updateReport' : IDL.Func([DailySiteReport], [], []),
  });
};

export const init = ({ IDL }) => { return []; };