/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Labour {
    id: bigint;
    dailyWage: number;
    role: string;
    projectId: bigint;
    daysWorked: number;
    workerName: string;
}
export interface DailySiteReport {
    id: bigint;
    workersOnSite: bigint;
    date: Time;
    hoursWorked: number;
    activities: string;
    projectId: bigint;
    notes: string;
    weather: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface BoqItem {
    id: bigint;
    plannedQuantity: number;
    unit: string;
    description: string;
    projectId: bigint;
    itemName: string;
    usedQuantity: number;
    unitRate: number;
}
export interface Material {
    id: bigint;
    supplier: string;
    name: string;
    unit: string;
    projectId: bigint;
    quantity: number;
    unitCost: number;
}
export interface ProjectCostSummary {
    status: ProjectStatus;
    remainingBudget: number;
    projectName: string;
    totalSpent: number;
    labourCost: number;
    projectId: bigint;
    materialsCost: number;
    budgetPct: number;
    budget: number;
}
export interface Project {
    id: bigint;
    estimatedDurationDays: number;
    status: ProjectStatus;
    endDate: Time;
    name: string;
    description: string;
    currentProgressPercentage: number;
    stage: ProjectStage;
    budget: number;
    location: string;
    startDate: Time;
}
export interface UserProfile {
    name: string;
}
export interface CostEntry {
    id: bigint;
    date: Time;
    description: string;
    projectId: bigint;
    category: string;
    amount: number;
}
export enum ProjectStage {
    foundation = "foundation",
    structure = "structure",
    completed = "completed",
    finishing = "finishing",
    planning = "planning"
}
export enum ProjectStatus {
    active = "active",
    completed = "completed",
    onHold = "onHold",
    planning = "planning"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBOQItem(item: BoqItem): Promise<bigint>;
    addCostEntry(cost: CostEntry): Promise<bigint>;
    addLabour(labour: Labour): Promise<bigint>;
    addMaterial(material: Material): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createProject(project: Project): Promise<bigint>;
    createReport(report: DailySiteReport): Promise<bigint>;
    deleteBOQItem(id: bigint): Promise<void>;
    deleteCostEntry(id: bigint): Promise<void>;
    deleteLabour(id: bigint): Promise<void>;
    deleteMaterial(id: bigint): Promise<void>;
    deleteProject(id: bigint): Promise<void>;
    deleteReport(id: bigint): Promise<void>;
    getAllProjectCostSummaries(): Promise<Array<ProjectCostSummary>>;
    getBoqItemsByProject(projectId: bigint): Promise<Array<BoqItem>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCostEntriesByProject(projectId: bigint): Promise<Array<CostEntry>>;
    getDashboardStats(): Promise<{
        foundationCount: bigint;
        onHoldCount: bigint;
        structureCount: bigint;
        completedCount: bigint;
        totalSpent: number;
        totalBudget: number;
        activeCount: bigint;
        planningCount: bigint;
        finishingCount: bigint;
    }>;
    getLabourByProject(projectId: bigint): Promise<Array<Labour>>;
    getMaterialsByProject(projectId: bigint): Promise<Array<Material>>;
    getProjectById(id: bigint): Promise<Project | null>;
    getProjectCostSummary(projectId: bigint): Promise<ProjectCostSummary | null>;
    getProjects(): Promise<Array<Project>>;
    getReportsByProject(projectId: bigint): Promise<Array<DailySiteReport>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateBOQItem(item: BoqItem): Promise<void>;
    updateCostEntry(cost: CostEntry): Promise<void>;
    updateLabour(labour: Labour): Promise<void>;
    updateMaterial(material: Material): Promise<void>;
    updateProject(id: bigint, updatedProject: Project): Promise<void>;
    updateReport(report: DailySiteReport): Promise<void>;
}
import type { Project as _Project, ProjectCostSummary as _ProjectCostSummary, ProjectStage as _ProjectStage, ProjectStatus as _ProjectStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBOQItem(arg0: BoqItem): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addBOQItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBOQItem(arg0);
            return result;
        }
    }
    async addCostEntry(arg0: CostEntry): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addCostEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCostEntry(arg0);
            return result;
        }
    }
    async addLabour(arg0: Labour): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addLabour(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLabour(arg0);
            return result;
        }
    }
    async addMaterial(arg0: Material): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addMaterial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMaterial(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createProject(arg0: Project): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(to_candid_Project_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(to_candid_Project_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createReport(arg0: DailySiteReport): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReport(arg0);
            return result;
        }
    }
    async deleteBOQItem(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBOQItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBOQItem(arg0);
            return result;
        }
    }
    async deleteCostEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCostEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCostEntry(arg0);
            return result;
        }
    }
    async deleteLabour(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLabour(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLabour(arg0);
            return result;
        }
    }
    async deleteMaterial(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMaterial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMaterial(arg0);
            return result;
        }
    }
    async deleteProject(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return result;
        }
    }
    async deleteReport(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReport(arg0);
            return result;
        }
    }
    async getAllProjectCostSummaries(): Promise<Array<ProjectCostSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProjectCostSummaries();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProjectCostSummaries();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBoqItemsByProject(arg0: bigint): Promise<Array<BoqItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBoqItemsByProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBoqItemsByProject(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCostEntriesByProject(arg0: bigint): Promise<Array<CostEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCostEntriesByProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCostEntriesByProject(arg0);
            return result;
        }
    }
    async getDashboardStats(): Promise<{
        foundationCount: bigint;
        onHoldCount: bigint;
        structureCount: bigint;
        completedCount: bigint;
        totalSpent: number;
        totalBudget: number;
        activeCount: bigint;
        planningCount: bigint;
        finishingCount: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getLabourByProject(arg0: bigint): Promise<Array<Labour>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLabourByProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLabourByProject(arg0);
            return result;
        }
    }
    async getMaterialsByProject(arg0: bigint): Promise<Array<Material>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMaterialsByProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMaterialsByProject(arg0);
            return result;
        }
    }
    async getProjectById(arg0: bigint): Promise<Project | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjectById(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjectById(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProjectCostSummary(arg0: bigint): Promise<ProjectCostSummary | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjectCostSummary(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjectCostSummary(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjects();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjects();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReportsByProject(arg0: bigint): Promise<Array<DailySiteReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReportsByProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReportsByProject(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateBOQItem(arg0: BoqItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBOQItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBOQItem(arg0);
            return result;
        }
    }
    async updateCostEntry(arg0: CostEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCostEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCostEntry(arg0);
            return result;
        }
    }
    async updateLabour(arg0: Labour): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLabour(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLabour(arg0);
            return result;
        }
    }
    async updateMaterial(arg0: Material): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMaterial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMaterial(arg0);
            return result;
        }
    }
    async updateProject(arg0: bigint, arg1: Project): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProject(arg0, to_candid_Project_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProject(arg0, to_candid_Project_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateReport(arg0: DailySiteReport): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReport(arg0);
            return result;
        }
    }
}
function from_candid_ProjectCostSummary_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectCostSummary): ProjectCostSummary {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectStage_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectStage): ProjectStage {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectStatus): ProjectStatus {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Project_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Project): Project {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Project]): Project | null {
    return value.length === 0 ? null : from_candid_Project_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProjectCostSummary]): ProjectCostSummary | null {
    return value.length === 0 ? null : from_candid_ProjectCostSummary_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ProjectStatus;
    remainingBudget: number;
    projectName: string;
    totalSpent: number;
    labourCost: number;
    projectId: bigint;
    materialsCost: number;
    budgetPct: number;
    budget: number;
}): {
    status: ProjectStatus;
    remainingBudget: number;
    projectName: string;
    totalSpent: number;
    labourCost: number;
    projectId: bigint;
    materialsCost: number;
    budgetPct: number;
    budget: number;
} {
    return {
        status: from_candid_ProjectStatus_n19(_uploadFile, _downloadFile, value.status),
        remainingBudget: value.remainingBudget,
        projectName: value.projectName,
        totalSpent: value.totalSpent,
        labourCost: value.labourCost,
        projectId: value.projectId,
        materialsCost: value.materialsCost,
        budgetPct: value.budgetPct,
        budget: value.budget
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    estimatedDurationDays: number;
    status: _ProjectStatus;
    endDate: _Time;
    name: string;
    description: string;
    currentProgressPercentage: number;
    stage: _ProjectStage;
    budget: number;
    location: string;
    startDate: _Time;
}): {
    id: bigint;
    estimatedDurationDays: number;
    status: ProjectStatus;
    endDate: Time;
    name: string;
    description: string;
    currentProgressPercentage: number;
    stage: ProjectStage;
    budget: number;
    location: string;
    startDate: Time;
} {
    return {
        id: value.id,
        estimatedDurationDays: value.estimatedDurationDays,
        status: from_candid_ProjectStatus_n19(_uploadFile, _downloadFile, value.status),
        endDate: value.endDate,
        name: value.name,
        description: value.description,
        currentProgressPercentage: value.currentProgressPercentage,
        stage: from_candid_ProjectStage_n27(_uploadFile, _downloadFile, value.stage),
        budget: value.budget,
        location: value.location,
        startDate: value.startDate
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    completed: null;
} | {
    onHold: null;
} | {
    planning: null;
}): ProjectStatus {
    return "active" in value ? ProjectStatus.active : "completed" in value ? ProjectStatus.completed : "onHold" in value ? ProjectStatus.onHold : "planning" in value ? ProjectStatus.planning : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    foundation: null;
} | {
    structure: null;
} | {
    completed: null;
} | {
    finishing: null;
} | {
    planning: null;
}): ProjectStage {
    return "foundation" in value ? ProjectStage.foundation : "structure" in value ? ProjectStage.structure : "completed" in value ? ProjectStage.completed : "finishing" in value ? ProjectStage.finishing : "planning" in value ? ProjectStage.planning : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProjectCostSummary>): Array<ProjectCostSummary> {
    return value.map((x)=>from_candid_ProjectCostSummary_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Project>): Array<Project> {
    return value.map((x)=>from_candid_Project_n25(_uploadFile, _downloadFile, x));
}
function to_candid_ProjectStage_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectStage): _ProjectStage {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_ProjectStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectStatus): _ProjectStatus {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_Project_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Project): _Project {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    estimatedDurationDays: number;
    status: ProjectStatus;
    endDate: Time;
    name: string;
    description: string;
    currentProgressPercentage: number;
    stage: ProjectStage;
    budget: number;
    location: string;
    startDate: Time;
}): {
    id: bigint;
    estimatedDurationDays: number;
    status: _ProjectStatus;
    endDate: _Time;
    name: string;
    description: string;
    currentProgressPercentage: number;
    stage: _ProjectStage;
    budget: number;
    location: string;
    startDate: _Time;
} {
    return {
        id: value.id,
        estimatedDurationDays: value.estimatedDurationDays,
        status: to_candid_ProjectStatus_n12(_uploadFile, _downloadFile, value.status),
        endDate: value.endDate,
        name: value.name,
        description: value.description,
        currentProgressPercentage: value.currentProgressPercentage,
        stage: to_candid_ProjectStage_n14(_uploadFile, _downloadFile, value.stage),
        budget: value.budget,
        location: value.location,
        startDate: value.startDate
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectStatus): {
    active: null;
} | {
    completed: null;
} | {
    onHold: null;
} | {
    planning: null;
} {
    return value == ProjectStatus.active ? {
        active: null
    } : value == ProjectStatus.completed ? {
        completed: null
    } : value == ProjectStatus.onHold ? {
        onHold: null
    } : value == ProjectStatus.planning ? {
        planning: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectStage): {
    foundation: null;
} | {
    structure: null;
} | {
    completed: null;
} | {
    finishing: null;
} | {
    planning: null;
} {
    return value == ProjectStage.foundation ? {
        foundation: null
    } : value == ProjectStage.structure ? {
        structure: null
    } : value == ProjectStage.completed ? {
        completed: null
    } : value == ProjectStage.finishing ? {
        finishing: null
    } : value == ProjectStage.planning ? {
        planning: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
