/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Material {
    id: bigint;
    supplier: string;
    name: string;
    unit: string;
    projectId: bigint;
    quantity: number;
    unitCost: number;
}
export interface DailySiteReport {
    id: bigint;
    workersOnSite: bigint;
    date: Time;
    hoursWorked: number;
    activities: string;
    projectId: bigint;
    notes: string;
    weather: string;
}
export type Time = bigint;
export interface Project {
    id: bigint;
    status: ProjectStatus;
    endDate: Time;
    name: string;
    description: string;
    budget: number;
    location: string;
    startDate: Time;
}
export interface UserProfile {
    name: string;
}
export interface CostEntry {
    id: bigint;
    date: Time;
    description: string;
    projectId: bigint;
    category: string;
    amount: number;
}
export enum ProjectStatus {
    active = "active",
    completed = "completed",
    onHold = "onHold",
    planning = "planning"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCostEntry(cost: CostEntry): Promise<bigint>;
    createMaterial(material: Material): Promise<bigint>;
    createProject(project: Project): Promise<bigint>;
    createReport(report: DailySiteReport): Promise<bigint>;
    deleteCostEntry(id: bigint): Promise<void>;
    deleteMaterial(id: bigint): Promise<void>;
    deleteProject(id: bigint): Promise<void>;
    deleteReport(id: bigint): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCostEntry(id: bigint): Promise<CostEntry | null>;
    getCostsByProject(projectId: bigint): Promise<Array<CostEntry>>;
    getDashboardStats(): Promise<{
        onHoldCount: bigint;
        completedCount: bigint;
        totalSpent: number;
        totalBudget: number;
        activeCount: bigint;
        planningCount: bigint;
    }>;
    getMaterial(id: bigint): Promise<Material | null>;
    getMaterialsByProject(projectId: bigint): Promise<Array<Material>>;
    getProject(id: bigint): Promise<Project | null>;
    getProjectSummary(projectId: bigint): Promise<{
        totalMaterialCost: number;
        totalCostEntries: number;
        variance: number;
        totalSpent: number;
        budget: number;
    }>;
    getProjectsByStatus(status: ProjectStatus): Promise<Array<Project>>;
    getReport(id: bigint): Promise<DailySiteReport | null>;
    getReportsByProject(projectId: bigint): Promise<Array<DailySiteReport>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateCostEntry(cost: CostEntry): Promise<void>;
    updateMaterial(material: Material): Promise<void>;
    updateProject(project: Project): Promise<void>;
    updateReport(report: DailySiteReport): Promise<void>;
}
import type { CostEntry as _CostEntry, DailySiteReport as _DailySiteReport, Material as _Material, Project as _Project, ProjectStatus as _ProjectStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCostEntry(arg0: CostEntry): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCostEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCostEntry(arg0);
            return result;
        }
    }
    async createMaterial(arg0: Material): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createMaterial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMaterial(arg0);
            return result;
        }
    }
    async createProject(arg0: Project): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(to_candid_Project_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(to_candid_Project_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createReport(arg0: DailySiteReport): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReport(arg0);
            return result;
        }
    }
    async deleteCostEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCostEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCostEntry(arg0);
            return result;
        }
    }
    async deleteMaterial(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMaterial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMaterial(arg0);
            return result;
        }
    }
    async deleteProject(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return result;
        }
    }
    async deleteReport(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReport(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCostEntry(arg0: bigint): Promise<CostEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCostEntry(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCostEntry(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCostsByProject(arg0: bigint): Promise<Array<CostEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCostsByProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCostsByProject(arg0);
            return result;
        }
    }
    async getDashboardStats(): Promise<{
        onHoldCount: bigint;
        completedCount: bigint;
        totalSpent: number;
        totalBudget: number;
        activeCount: bigint;
        planningCount: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getMaterial(arg0: bigint): Promise<Material | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMaterial(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMaterial(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMaterialsByProject(arg0: bigint): Promise<Array<Material>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMaterialsByProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMaterialsByProject(arg0);
            return result;
        }
    }
    async getProject(arg0: bigint): Promise<Project | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProject(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProject(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProjectSummary(arg0: bigint): Promise<{
        totalMaterialCost: number;
        totalCostEntries: number;
        variance: number;
        totalSpent: number;
        budget: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjectSummary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjectSummary(arg0);
            return result;
        }
    }
    async getProjectsByStatus(arg0: ProjectStatus): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjectsByStatus(to_candid_ProjectStatus_n5(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjectsByStatus(to_candid_ProjectStatus_n5(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReport(arg0: bigint): Promise<DailySiteReport | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReport(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReport(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReportsByProject(arg0: bigint): Promise<Array<DailySiteReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReportsByProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReportsByProject(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateCostEntry(arg0: CostEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCostEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCostEntry(arg0);
            return result;
        }
    }
    async updateMaterial(arg0: Material): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMaterial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMaterial(arg0);
            return result;
        }
    }
    async updateProject(arg0: Project): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProject(to_candid_Project_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProject(to_candid_Project_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateReport(arg0: DailySiteReport): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReport(arg0);
            return result;
        }
    }
}
function from_candid_ProjectStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectStatus): ProjectStatus {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Project_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Project): Project {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CostEntry]): CostEntry | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Material]): Material | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Project]): Project | null {
    return value.length === 0 ? null : from_candid_Project_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DailySiteReport]): DailySiteReport | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ProjectStatus;
    endDate: _Time;
    name: string;
    description: string;
    budget: number;
    location: string;
    startDate: _Time;
}): {
    id: bigint;
    status: ProjectStatus;
    endDate: Time;
    name: string;
    description: string;
    budget: number;
    location: string;
    startDate: Time;
} {
    return {
        id: value.id,
        status: from_candid_ProjectStatus_n15(_uploadFile, _downloadFile, value.status),
        endDate: value.endDate,
        name: value.name,
        description: value.description,
        budget: value.budget,
        location: value.location,
        startDate: value.startDate
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    completed: null;
} | {
    onHold: null;
} | {
    planning: null;
}): ProjectStatus {
    return "active" in value ? ProjectStatus.active : "completed" in value ? ProjectStatus.completed : "onHold" in value ? ProjectStatus.onHold : "planning" in value ? ProjectStatus.planning : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Project>): Array<Project> {
    return value.map((x)=>from_candid_Project_n13(_uploadFile, _downloadFile, x));
}
function to_candid_ProjectStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectStatus): _ProjectStatus {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Project_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Project): _Project {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: ProjectStatus;
    endDate: Time;
    name: string;
    description: string;
    budget: number;
    location: string;
    startDate: Time;
}): {
    id: bigint;
    status: _ProjectStatus;
    endDate: _Time;
    name: string;
    description: string;
    budget: number;
    location: string;
    startDate: _Time;
} {
    return {
        id: value.id,
        status: to_candid_ProjectStatus_n5(_uploadFile, _downloadFile, value.status),
        endDate: value.endDate,
        name: value.name,
        description: value.description,
        budget: value.budget,
        location: value.location,
        startDate: value.startDate
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectStatus): {
    active: null;
} | {
    completed: null;
} | {
    onHold: null;
} | {
    planning: null;
} {
    return value == ProjectStatus.active ? {
        active: null
    } : value == ProjectStatus.completed ? {
        completed: null
    } : value == ProjectStatus.onHold ? {
        onHold: null
    } : value == ProjectStatus.planning ? {
        planning: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
